buffsToTrack = {
  {
    name = "Food",
    searchTerms = { "well fed" },
    icon = "Interface/Icons/Spell_Misc_Food",
    classes = {},
    selfOnly = false,
    personalBuff = true,
  },
  {
    name = "Flask",
    searchTerms = { "flask", "phial" },
    icon = "Interface/Icons/INV_Alchemy_90_Flask_Green",
    classes = {},
    selfOnly = false,
    personalBuff = true,
  },
  {
    name = "Weapon Buffs",
    searchTerms = {},
    icon = "Interface/Icons/Spell_DeathKnight_FrozenRuneWeapon",
    classes = {},
    selfOnly = false,
    personalBuff = true,
  },
  {
    name = "Rune",
    searchTerms = {
      "void%-touched",
      "crystallization",
    },
    icon = "Interface/Icons/INV_Misc_Gem_AzureDraenite_01",
    classes = {},
    selfOnly = false,
    personalBuff = true,
  },
  {
    name = "Healthstone",
    searchTerms = {},
    icon = "Interface/Icons/INV_stone_04",
    classes = {},
    selfOnly = false,
    personalBuff = true,
  },
  {
    name = "Battle Shout",
    searchTerms = { "battle shout" },
    icon = "Interface/Icons/Ability_Warrior_BattleShout",
    classes = { "WARRIOR" },
    selfOnly = false,
  },
  {
    name = "Mark of the Wild",
    searchTerms = { "mark of the wild" },
    icon = "Interface/Icons/Spell_Nature_Regeneration",
    classes = { "DRUID" },
    selfOnly = false,
  },
  {
    name = "Power Word Fortitude",
    searchTerms = { "power word: fortitude" },
    icon = "Interface/Icons/Spell_Holy_WordFortitude",
    classes = { "PRIEST" },
    selfOnly = false,
  },
  {
    name = "Arcane Intellect",
    searchTerms = { "arcane intellect" },
    icon = "Interface/Icons/Spell_Holy_MagicalSentry",
    classes = { "MAGE" },
    selfOnly = false,
  },
  {
    name = "Skyfury",
    searchTerms = { "skyfury" },
    icon = "Interface/Icons/Achievement_raidprimalist_windelemental",
    classes = { "SHAMAN" },
    selfOnly = false,
  },
  {
    name = "Blessing of The Bronze",
    searchTerms = { "blessing of the bronze" },
    icon = "Interface/Icons/ability_evoker_blessingofthebronze",
    classes = { "EVOKER" },
    selfOnly = false,
  },
  {
    name = "Water/Lightning Shield",
    searchTerms = { "water shield", "lightning shield" },
    icon = "Interface/Icons/Spell_Nature_LightningShield",
    classes = { "SHAMAN" },
    selfOnly = true,
  },
  {
    name = "Earth Shield",
    searchTerms = { "earth shield" },
    icon = "Interface/Icons/Spell_Nature_SkinOfEarth",
    classes = { "SHAMAN" },
    selfOnly = true,
  },
  {
    name = "Symbiotic Relationship",
    searchTerms = { "symbiotic relationship" },
    icon = "Interface/Icons/ability_druid_focusedgrowth",
    classes = { "DRUID" },
    selfOnly = true,
  },
}
